### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by EH-HU** [whitecrow1027/CrossSP_Depth#2]
I downloaded the dataset from your link, but the files written in the txt file in the data directory do not exist.
I have only 5092 training images and 1928 test images.

**Comment by whitecrow1027** [comment]
Thank you for submitting the issue. I will review the uploaded data recently. If there are any missing elements, I will update the dataset accordingly.

**Comment by EH-HU** [comment]
Thank you for your answer. Could you check and let me know?

**Comment by whitecrow1027** [comment]
> Thank you for your answer. Could you check and let me know?

Hello, I checked the uploaded data and found that I gave a wrong data partition. I update the dataset download link to the right one.
